### ISSUE TITLE
[BUG] Cant upload larger files

### ISSUE THREAD

**Issue by suse-coder** [opencloud-eu/ios#18]
When I upload smaller files (50MB) then the upload to opencloud server works fine. But a larger one (1GB) gives an error:

Der Vorgang konnte nicht abgeschlossen werden
OCHTTPStatusErrorDomain Fehler 507

Login is done through keycloak SSO.

### Steps to reproduce
1. Upload larger file (1GB)

### Expected behavior
Upload large file

### Actual behavior
Error upload

### Client
**iOS version:** version 1.0.1 build 3

**OpenCloud app version:** 2.3.0

**Device model:** iphone se version 18.5

### Server configuration
**OpenCloud version:**

#### OpenCloud server error log
```
Insert your OpenCloud server log here
```

**Comment by TheOneRing** [comment]
Can you check the timeout for your reverse proxy is correctly set? See https://github.com/opencloud-eu/opencloud/blob/9462ad524f15480bf99cedc9f5a48d4b362f319c/deployments/examples/opencloud_full/docker-compose.yml#L23-L26 for traefik.

**Comment by suse-coder** [comment]
We use cilium gateway api. Its not a problem with the gateway. Via Browser no problem.

**Comment by TheOneRing** [comment]
We assume we discovered the issue, the files are not chunked. But if a timeout of 60s is set it would explain the aborted upload but could also cause other issues.

**Comment by guruz** [comment]
@suse-coder Do you see the iOS client using TUS for uploading? e.g. in the server log, do you see a POST for creation of the file and then PATCH calls for the file chunks?

**Comment by zerox80** [comment]
> We assume we discovered the issue, the files are not chunked. But if a timeout of 60s is set it would explain the aborted upload but could also cause other issues.

But when i implemented the Android TUS i used the IOS as reference, i am not sure but i think the Path in the ios sdk is wrong. Maybe thats why its not chunking. I had to look in the server repo as reference to finish the tus implementation of the android project. Correct me if im wrong

**Comment by TheOneRing** [comment]
@guruz did you find out why TUS isn't used?

**Comment by johanneskastl** [comment]
Any news on this? I think I am hitting this on a iPhone, where I had to manually `Retry` multiple times to get some bigger files synced...

**Comment by heavenssealer** [comment]
Hi, seems like the issue still persists. I can't upload any files larger than 100MB via the app, while no issue via the browser (or on desktop).

**Comment by kulmann** [comment]
@guruz looks like in some contexts (with memory configuration `minimum`) the TUS chunking is ignored, see https://github.com/opencloud-eu/ios-sdk/blob/95e45b3bbd58e748d21bcf873c9f7267f3155f9a/OpenCloudSDK/Connection/OCConnection%2BUpload.m#L252

Does that even make sense? Chunks are read from storage, not from memory, so chunking doesn't increase the memory pressure (or does it)? Maybe that's the cause?

**Comment by guruz** [comment]
@suse-coder @johanneskastl @heavenssealer Could you tell me **how you exactly upload**? There are different code paths depending on if you upload directly from the OC app or if you are inside another app and share to OC etc etc..

@kulmann Thankss, interesting line... might be bogus...

**Comment by suse-coder** [comment]
Have not tested it again for a while. But I just in the app select a large file to upload.
